[package]
name = "deboa-test-utils"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bytes = { workspace = true }
caramelo = { workspace = true }
ciborium = "0.2.2"
deboa.workspace = true
deboa-extras = { workspace = true, default-features = false, features = [
  "serialization_all",
] }
deboa-fory = { workspace = true, default-features = false }
deboa-macros = { workspace = true }
easyhttpmock = "0.1.3"
env_logger = "0.11.11"
fory = "1.5.0"
fory-core = "1.5.0"
futures-util = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
mime = { version = "0.3.17" }
multer = "3.1.0"
once_cell = "1.21.4"
rand = { workspace = true }
serde = { workspace = true }
tackle = { workspace = true }
url = { workspace = true }
vamo = { workspace = true, default-features = false }
vamo-macros = { workspace = true, features = [
  "json",
], default-features = false }
vetis = "0.1.4"
